import Head from 'next/head'
import { Inter } from '@next/font/google'
import DateRangePicker from '../components/DateRangePicker';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome</h1>
      <DateRangePicker />
    </>
  )
}
